name: "Build and Sign"
on:
  push:

jobs:
  build:
    if: contains(github.event.head_commit.message, '-build')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Release Cert
        working-directory: ./
        env:
          GTO_CERTIFICATE: ${{ secrets.GTO_CERT }}
        run: |
          echo $GTO_CERTIFICATE | base64 --decode > keystore.jks

      - uses: burrunan/gradle-cache-action@v3
        name: Build GTOCore
        env:
          GTO_STOREPASS: ${{ secrets.GTOKEY }}
          GTO_KEYPASS: ${{ secrets.GTOKEY }}
        with:
          job-id: jdk21
          arguments: build
          gradle-version: wrapper

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/libs
          retention-days: 1
